//
// Created by Olcay Taner Yıldız on 12.10.2018.
//

#ifndef XMLPARSER_XMLTOKENTYPE_H
#define XMLPARSER_XMLTOKENTYPE_H

enum class XmlTokenType{
    XML_OPENING_TAG_WITH_ATTRIBUTES = 0,
    XML_OPENING_TAG_WITHOUT_ATTRIBUTES,
    XML_OPENING_TAG_FINISH,
    XML_CLOSING_TAG_WITH_ATTRIBUTES,
    XML_CLOSING_TAG_WITHOUT_ATTRIBUTES,
    XML_ATTRIBUTE_VALUE,
    XML_EQUAL,
    XML_TEXT,
    XML_END
};
#endif //XMLPARSER_XMLTOKENTYPE_H
